name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        override: true
        components: rust-src, llvm-tools-preview
    - name: Install bootimage
      run: cargo install bootimage
    - name: Install QEMU
      run: sudo apt install -y qemu-system-x86
    - name: Build and test
      run: cargo test --verbose
