name: clippy
on: pull_request
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get clippy
        run: rustup component add clippy
      - name: Check
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          toolchain: nightly
